#################
## MY PROGRAMS ##
#################
$sriptsFolder = ~/.config/hypr/scripts


$terminal = ghostty
$fileManager = thunar 
$browser = firefox
$menu = rofi -show drun
$cursor = volantes_cursors
$cursorSize = 24
